name: "🐛 Bug Report"
description: "Create a report to help us improve PromptVault"
title: "[BUG] "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛  
        Please provide as much detail as possible.

  - type: textarea
    id: bug-description
    attributes:
      label: "🐛 Bug Description"
      description: "What went wrong?"
      placeholder: "Describe the bug clearly and concisely..."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "🔄 Steps to Reproduce"
      description: "How can we reproduce the issue?"
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "✅ Expected Behavior"
      description: "What should have happened instead?"
      placeholder: "Describe the correct behavior..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: "❌ Actual Behavior"
      description: "What actually happened?"
      placeholder: "Describe the actual behavior..."
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: "🖥️ Environment"
      description: "Details about your setup"
      placeholder: |
        - OS: Windows 11 / macOS 13 / Ubuntu 22.04
        - Browser: Chrome 120 / Firefox 121 / Safari 17
        - PromptVault Version: 1.0.0
    validations:
      required: true

  - type: textarea
    id: console-logs
    attributes:
      label: "🔍 Logs / Console Output"
      description: "Paste relevant logs or error messages here (if any)."
      placeholder: |
        // Browser console logs
        console.error("Error message here");

        # Backend logs
        [ERROR] Error message here

  - type: checkboxes
    id: checklist
    attributes:
      label: "📝 Checklist"
      description: "Please confirm you have done the following:"
      options:
        - label: "I have searched existing issues to avoid duplicates"
        - label: "I have provided all the requested information"
        - label: "I can reproduce this issue consistently"
    validations:
      required: true
