name: 🐛 Bug Report
description: Create a report to help us improve PromptVault
title: '[BUG] '
labels: ['bug']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛
        
        Please provide as much detail as possible to help us understand and fix the issue.
  
  - type: textarea
    id: bug-description
    attributes:
      label: 🐛 Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug in detail...
    validations:
      required: true
  
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  
  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should happen when you follow the steps above?
    validations:
      required: true
  
  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened when you followed the steps above?
    validations:
      required: true
  
  - type: markdown
    attributes:
      value: |
        ## 📸 Screenshots
        
        If applicable, add screenshots to help explain your problem.
  
  - type: markdown
    attributes:
      value: |
        ## 🖥️ Environment
        
        **Desktop (please complete the following information):**
        - OS: [e.g. Windows 11, macOS 13, Ubuntu 22.04]
        - Browser: [e.g. Chrome 120, Firefox 121, Safari 17]
        - Version: [e.g. 22]
        
        **Mobile (please complete the following information):**
        - Device: [e.g. iPhone 15, Samsung Galaxy S24]
        - OS: [e.g. iOS 17, Android 14]
        - Browser: [e.g. Safari, Chrome]
        - Version: [e.g. 22]
  
  - type: markdown
    attributes:
      value: |
        ## 📱 Application Details
        
        - **PromptVault Version**: [e.g. 1.0.0]
        - **Backend Version**: [e.g. 1.0.0]
        - **Database**: [e.g. SQLite, PostgreSQL]
  
  - type: textarea
    id: additional-context
    attributes:
      label: 📋 Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - When did this issue start occurring?
        - Does it happen with all users or just specific ones?
        - Are there any error messages in the browser console?
        - Are there any error messages in the backend logs?
  
  - type: textarea
    id: console-logs
    attributes:
      label: 🔍 Console Logs
      description: If applicable, please include relevant console logs
      placeholder: |
        // Browser console logs
        console.error('Error message here');
        
        # Backend logs
        [ERROR] Error message here
  
  - type: checkboxes
    id: checklist
    attributes:
      label: 📝 Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
        - label: I have provided all the requested information
        - label: I can reproduce this issue consistently
        - label: This issue is not related to my local environment setup
    validations:
      required: true
  
  - type: textarea
    id: related-issues
    attributes:
      label: 🏷️ Related Issues
      description: Link any related issues here using the # symbol (e.g., #123)
      placeholder: #123, #456
  
  - type: markdown
    attributes:
      value: |
        ---
        
        **Note**: Please be respectful and constructive in your bug reports. We're here to help improve PromptVault together! 🚀
